version: '3'
services:
  nginx:
   image: 'nginx:alpine'
   depends_on:
      - ghost
   volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
   ports:
      - '80:80'
   networks:
      - proxy
  mysql:
    image: 'mysql'
    container_name: 'mysql'
    ports:
      - '3306:3306'
    volumes:
      - ./volumes:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=123
    networks:
      - db
  ghost:
    image: 'ghost:alpine'    
    container_name: 'ghost'
    volumes:
      - ./config.production.json:/var/lib/ghost/config.production.jsons
    depends_on:
      - 'mysql'
    networks:
      - proxy
      - db
networks:
  proxy:
  db: